execute pathogen#infect()
syntax on
filetype plugin indent on

colo darkblue

" Configuration vim Airline
" set laststatus=2
"
" let g:airline#extensions#tableine#enabled=1
" let g:airline_powerline_fonts=1
"
